### PR TITLE
adding config for background colors

### PR DESCRIPTION
**Pull request by eperedo**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8693cf1fh

### :memo: Implementation

Since a section has 3 different containers we have the option to add the background color for: title, columns and rows:

image

Here we have pink for the title, brown for the columns and gray for the rows. In order to get this we need to add the styles object into the config:

```json
{
  "sections": {
        "MAL_CONTACT_INFORMATION": {
            "styles": {
                "columns": {
                  "backgroundColor": "#cd853f"
                },
                "rows": {
                  "backgroundColor": "#F7F7F7"
                },
                "title": {
                  "backgroundColor": "#FFC0CB"
                }
          },
          "viewType": "table"
      },
  }
}
```

### Limitations:

Having different colors for a particular set of rows in the same section is not possible right now.
image

If we want to support this first we need to implement a feature that allows adding sections inside sections so we can differentiate and apply colors to each one. Seems tricky right now since DHIS does not have the concept of subsections.

### :art: Screenshots

image

image

image

### :fire: Notes to the tester

Example json configuration attached in the issue

### CODE REVIEW

**Comment by MiquelAdell** [comment]
Thanks for the work @eperedo 

I can not reproduce the look you provided in screenshots.

I'm using yarn start on the current branch and using this url to check:
http://192.168.68.71:8081/?orgUnit=jFOZHDZpjPL&dataSet=PWCUb3Se1Ie&period=2022

This identifies Angola and the dataset WMR Form.

I have uploaded the provided json file using data store editor in dev because the current "autogenerated-forms-configurator" tool is highlighting errors in the JSON that blocks it from saving:
Screenshot 2024-01-03 at 10 16 41

The new way to save autogen form configuration is using this tool. It can be accessed by setting
```REACT_APP_REPORT_VARIANT=autogenerated-forms-configurator``` in .env.local and running ```yarn start```

I have also installed the latest version in dev so you can access it directly here:
https://dev.eyeseetea.com/who-dev-238/api/apps/Autogen-form-editor/index.html

The form I see is this:
image

Is there something I'm doing wrong testing-wise?

You can edit dev's datastore/d2-autogen-forms/MAL-WMR to test this functionality.

Regarding the limitation (subsections) let's leave it like it is at the moment.

**Comment by eperedo** [comment]
> Thanks for the work @eperedo
> 
> I can not reproduce the look you provided in screenshots.
> 
> I'm using yarn start on the current branch and using this url to check: http://192.168.68.71:8081/?orgUnit=jFOZHDZpjPL&dataSet=PWCUb3Se1Ie&period=2022
> 
> This identifies Angola and the dataset WMR Form.
> 
> I have uploaded the provided json file using data store editor in dev because the current "autogenerated-forms-configurator" tool is highlighting errors in the JSON that blocks it from saving: Screenshot 2024-01-03 at 10 16 41
> 
> The new way to save autogen form configuration is using this tool. It can be accessed by setting `REACT_APP_REPORT_VARIANT=autogenerated-forms-configurator` in .env.local and running `yarn start`
> 
> I have also installed the latest version in dev so you can access it directly here: https://dev.eyeseetea.com/who-dev-238/api/apps/Autogen-form-editor/index.html
> 
> The form I see is this: image
> 
> Is there something I'm doing wrong testing-wise?
> 
> You can edit dev's datastore/d2-autogen-forms/MAL-WMR to test this functionality.
> 
> Regarding the limitation (subsections) let's leave it like it is at the moment.

The dataSet does not have any dataElements on dev, not sure the reason (maybe a bad sync?) I will update the metadata

image

**Comment by eperedo** [comment]
I have updated the config for MAL-WMR-OLD dataSet while I try to recover the other dataSet.

You can give it a try: http://localhost:8082/?dataSetId=JbaKAw8pbJl&dataSet=JbaKAw8pbJl&orgUnit=bGWaeVBrOcc&period=2022

You cannot use the Autogen-form-editor right now because the current configuration has sections that do not exist on the dataSet (all the ones that starts with **LBL_**).

**Review by MiquelAdell — APPROVED** [review]
I have issues with the configuration but it is related to the json configuration not the colours. I can see the colours correctly so I'm accepting the pull request.

Thanks!

**Pull request merged**
